#!/bin/sh

# Starting all of the required programs.
pkill polybar || polybar "fds-bar" &
pkill feh || feh $HOME/.background-image

# Removing all rules at startup to prevent duplicating rules. 
bspc rule -r "*"

# Set up the desktops (workspaces) for the monitor
bspc monitor -d I II III IV V 

bspc config border_width        2
bspc config window_gap          9

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_border_color "#88C0D0"
bspc config focus_follows_pointer true

# Set the default cursor to pointer
xsetroot -cursor_name left_ptr

# Rules
bspc rule -a code-oss desktop=^2
bspc rule -a firefox desktop=^1

