#!/usr/bin/env sh

# Open all of the programs needed.
pkill polybar; polybar "fds-bar" &
pkill feh; feh --bg-fill $HOME/.background-image
pkill dunst; dunst &

# Removing all rules at startup to prevent duplicating rules.
bspc rule -r "*"

# Set up the desktops (workspaces) for the monitor
bspc monitor -d web text dev graphics 3d mail music vm

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_border_color "#e9d3ce"
bspc config focus_follows_pointer true

# Set the default cursor to pointer
xsetroot -cursor_name left_ptr

# Rules
bspc rule -a code-oss desktop=^2
bspc rule -a firefox desktop=^1
bspc rule -a emacs state=tiled

