keys:
  - &foo-dogsquared 7C7F9DC0694508015FE4C9F2DD5E7C08041214EE
  - &foo-dogsquared-old 8FCE86932583783E515B6FE55F2B001E20ED3763
  - &foo-dogsquared-old-2 DDD7D0BD602E564BAA04FC3514310D9141152B92
  - &foo-dogsquared-age age17he74we2sm7q7ufv6x26n83hs42v6gkj984m6kwf9xtjduyccqmqtpv37q
  - &ni age1jxna9vm7nx4g69s84qgjptxvuzszcypf2rfk4ss2lyhnpe3yxdnqusu6jp
  - &plover age1yftkhugwrdnlpl45lthrhvvk720zza2nd085sxvjcxg2guavz3kquktplx
creation_rules:
  - path_regex: configs/nixos/ni/(modules/.+/secrets|secrets/[^/]+)\.(yaml|json|ini|env)$
    age: *ni
  - path_regex: configs/nixos/plover/(modules/.+/secrets|secrets/[^/]+)\.(yaml|json|ini|env)$
    age: *plover
  - path_regex: configs/home-manager/foo-dogsquared/(modules/.+/secrets|secrets/[^/]+)\.(yaml|json|inienv)$
    age: *foo-dogsquared-age
