= foo-dogsquared's NixOS config
:toc:
:devos_link: https://github.com/divnix/digga/tree/580fc57ffaaf9cf3a582372235759dccfe44ac92/examples/devos
:doc_site: https://foo-dogsquared.github.io/nixos-config
:canonical_flake_url: github:foo-dogsquared/nixos-config
:canonical_flake_url_tarball_master: https://github.com/foo-dogsquared/nixos-config/archive/master.tar.gz
:canonical_flake_url_tarball_specific: https://github.com/foo-dogsquared/nixos-config/archive/35c27749c55077727529f412dade862e4deb2ae8.tar.gz

This is my NixOS config as a link:https://www.tweag.io/blog/2020-05-25-flakes/[Nix flake] eventually containing my (almost) complete setup from a desktop, to a server, to a personalized installer, almost everything.
This configuration setup can be described with a list of features:

* Deploy the same NixOS configuration for more than one system.
This is configured with the link:./images.toml[./images.toml] where not only you can deploy them with https://github.com/serokell/deploy-rs[deploy-rs] but build them as generated by https://github.com/nix-community/nixos-generators[nixos-generators].
You can even configure what nixpkgs branch (and home-manager branch) it will use.

* Similarly, deploy the same home-manager configuration for more than one system.
This time, it is configured with the link:./users.toml[./users.toml] file which you can configure what nixpkgs branch it will use.

* Unify https://github.com/nix-community/nixos-generators[home-manager] and NixOS configuration (and maybe other environments such as nix-darwin and system-manager in case I have use cases for those) into one flake.

* Take full advantage of Nix module system with the cluster-wide custom modules footnote:[Most of them are patterned similarly from nixpkgs which made easy to be upstreamed just in case.].
This design bleeds into configuring the NixOS systems and home-manager users by designing {doc-site}/04-nixos-modules/04-host-specific-modules/[host-specific modules] and {doc-site}/05-home-manager/#_user_specific_modules[user-specific modules], respectively.

* It has its own {doc-site}[website].
Which means that it's cool (or over-the-top, whichever you prefer).

It's basically my personal version of nixpkgs: a monorepo of everything I need for Nix-related things (unless it sprung into life as its own project).

Anyways, this project also has a dedicated website at {doc_site} which I recommend to take a gander on how this project structures its configuration (and much of the information is not covered in this README anyways).
If you want the local documentation and has angst against online documentation, you can view the source code of the book at link:./docs/[`./docs/`].




== Getting started

This is an overencumbered set of NixOS configurations for different systems.
For this section though, we'll assume you're only interested in installing the desktop configuration.

To start, you'll have to download a NixOS installer image.
While you can download link:https://releases.nixos.org/?prefix=nixos/unstable/[the latest revisions from the official website], you can get my personalized installer from link:https://github.com/foo-dogsquared/nixos-config/releases/tag/latest[the releases page of this project].
Next, boot into the installer image.
Then as root, install the desktop with the following commands.

[source, shell, subs=attributes]
----
bash $(nix build --no-link --print-out-paths {canonical_flake_url}#nixosConfigurations.ni.config.system.build.diskoScript)
nixos-install --flake {canonical_flake_url}#ni
----

The above command will automate everything for you including the partitioning steps.

Voila!
You should have my desktop configuration installed.

However, it should also be barely usable since there are a couple of missing components that are needed such as the private keys for the desktop which is required for certain tasks such as backup task with Borg among other things.
There are also some additional prerequisites such as partitioning which is already handled with link:https://github.com/nix-community/disko[disko].




== Using the flake

If you want to use the flake as part of the flake inputs, you can simply include it in `flake.nix`.

[source, nix]
----
{
    inputs.foodogsquared-flake.url = "github:foo-dogsquared/nixos-config";
}
----

For a better experience, I recommend using https://flakehub.com/flake/foo-dogsquared/nixos-config[FlakeHub] (with available instructions in the linked page).
The FlakeHub flake follows a rolling release model so all of the releases are under 0.x.




== Stability promise

If you're one of the unfortunate users for whatever reason, sorry but there's no stability promise here.
Not every commit successfully builds because of the way how the project is managed (which is very very badly):

* All of the included changes are pushed in one fell swoop over time instead of carefully testing each of them.
* NixOS and home-manager configurations are able to be deployed in pure evaluation mode and suddenly it's not (most of the time, it isn't).
* Module interfaces change all the time.
* Packages can be left unmaintained and vanish at any time. footnote:[The ones I actively maintain are in nixpkgs anyways.]

This is my personal NixOS configuration, after all.
It serves more of a platform to experiment with the Nix ecosystem rather than something that it's meant to be used by others.
There are some parts of the configuration that eventually sprung as its own project such as the https://github.com/foo-dogsquared/nix-overlay-guix[Guix overlay] (which eventually upstreamed into nixpkgs, hoorah!).
Hopefully, more of them can be like that in the future (provided I still use Nix and have some time for it).




== TODO

In order of priority:

* [x] Create custom modules.
* [x] Create a themes system similar to link:https://github.com/hlissner/dotfiles[this NixOS config].
* [x] Create a good workflow for creating ISOs.
* [x] Create development shells.
* [x] Manage secrets with agenix.
* [ ] Create a good workflow for tests.
* [x] Automate backups with NixOS config.
* [x] Create custom packages and export it to flakes. (Maybe consider making it to upstream)
* [x] Create cluser-wide configs.
* [x] Create host-wide configs.
* [x] Create user-specific configs with home-manager.
* [x] ~Steal~ Get some ideas from link:{devos_link}[this overengineered template].
* [x] Make use of other established utilities such as link:https://github.com/divnix/digga/[digga], link:https://github.com/gytis-ivaskevicius/flake-utils-plus[flake-utils-plus], and link:https://github.com/nix-community/home-manager[home-manager] once I'm familiar to create my own Nix programs.


=== Out of scope:

* Set most program configurations with Nix.
This is especially applicable to programs I always use such as my text editor configs.

** The reason: managing them can be chaotic when applied with Nix.
The potential for it is pretty nice especially when seen with similar implementations such as Guix home environment.
However, I don't want to rebuild it every time I change it.

* Migration of my link:https://github.com/foo-dogsquared/dotfiles[dotfiles].
I still use it on other non-NixOS systems.

* To be a configuration framework.
This is my personal configuration which means experimentation will always be here.
Sudden changes can happen at any point.




== Copyright

This project is licensed under MIT license.
I just chose it to make it easier to upstream parts of this project to nixpkgs and to make it easier to copy it without much problems (just don't forget to add attribution as indicated from the license).
Please see link:./LICENSE[`./LICENSE`] for the full text.
