[global]
excludes = [
  "pkgs/firefox-addons/default.nix"
  "subprojects"
]

[formatter.lua]
command = "stylua"
includes = [ "*.lua" ]

[formatter.nix]
command = "nixfmt"
includes = [ "*.nix" ]

[formatter.python]
command = "black"
includes = [ "*.py" ]

[formatter.terraform]
command = "tofu"
options = [ "fmt" ]
includes = [ "*.tf" ]
