= wrapper-manager-configuration(5)
:doctype: manpage
:mantitle: WRAPPER-MANAGER-CONFIGURATION.NIX(5)
:manmanual: wrapper-manager configuration
:mansource: wrapper-manager configuration
:man-linkstyle: pass:[blue R < >]


== Name

wrapper-manager-configuration.nix - wrapper-manager configuration specification

ifdef::is-wider-scoped[]
== Additional notes

If you've included env-specific integration wrapper-manager modules (e.g., NixOS, home-manager), there are additional things that are included.

* The wider-scoped environment configuration is included as a module argument in each wrapper-manager package (i.e., `wrapper-manager.packages`).
This is mainly useful to create a dynamic wrapper-manager package with different parameters when in NixOS, home-manager, or as standalone package.
+
--
* For NixOS integration, the NixOS configuration is available as `nixosConfig`.
* For home-manager integration, `hmConfig` stores the home-manager configuration.
--

* Additional wrapper-manager documentation can be deployed with the wider environment.
So far, there should be a manpage or an HTML document that can be enabled with `wrapper-manager.documentation.{manpage,html}.enable`.
endif::[]

== Options
