= User-specific configuration
:toc:

This is where user-specific configurations comes in.
Similar to modules, the top-level of this directory contains users for various modules (e.g., home-manager, NixOS).

Take note of the following structure:

[source, tree]
----
users/
├── home-manager/
│   ├── foo-dogsquared/
│   ├── harepoint/
│   └── polski/
├── nixos/
│   ├── foo-dogsquared/
│   ├── harepoint/
│   └── vmguest/
└── README.adoc
----

It doesn't require to have users to be present for all types.
There are conventions for setting in each user type.

* For NixOS user configuration, it is expect to only have one user with their respective user-specific configuration.
This includes user-specific packages, home-manager-specific configuration (even importing them from `./home-manager` users), and so forth.
If you want to set users from the host, see link:../hosts/README.adoc[Host-specific configurations] for more details.

* home-manager users are just home-manager configurations (i.e., `$XDG_CONFIG_HOME/nix/home.nix`).
That's pretty much it.
