---
title: Introduction
---
= Introduction

Hey there, fellow traveler!
You've fell into the rabbit hole we call Nix where it leads to other rabbit holes such as functional package management, reproducibility, declarative systems, and immutable operating systems.

Legends say the rabbit hole runs so deep you'll eventually spend hours to create a dedicated website only for your NixOS configuration.
However, I haven't seen this for myself nor I see much examples of it.
But it is just mere legend anyways for a radically different package management, operating system, and deployment method, so who cares really.

Anyways...
What you're seeing right now is the documentation for my NixOS configuration as a link:https://www.tweag.io/blog/2020-05-25-flakes/[Nix flake].
It eventually evolves as a massive blob of abomination that will surely get simpler as time go by.

Take note this configuration serves as a platform for experimenting with the Nix ecosystem.
It is a personal configuration after all so all changes can happen on a whim including adding a component into the Nix systems, removing a flake input, __et cetera__ and __et cetera__.

This documentation serves as an overview for what I'm looking into the Nix ecosystem and hopefully can help some poor soul treading through the documentation (or lack thereof) present in the ecosystem.
Otherwise, it's just a project just to be a showoff that I have a dedicated website for my configuration, MUAHAHAHAHAHAH!

[chat, Ezran, role=reversed]
====
I feel this project exists for the latter point in that last paragraph.
====

[chat, foodogsquared]
====
Yeah, so?
====

[chat, Ezran, role=reversed]
====
You do you.
Your project, your rules.
====
