---
title: Acknowledgment
---
= Acknowledgment

Several parts of this configuration are inspired (or stolen) from the following projects:

* github:NixOS/nixpkgs[opts=repo] as a massive reference for drafting various packages and modules.
Much of the custom packages I have was eventually upstreamed (or eventually forgotten).

* github:nix-community/NUR[opts=repo] is a nice reference for making your configurations reusable for other users.

* link:{devos-link}[devos, an overengineered configuration framework.]
I'm slowly grokking Nix and its ecosystem so I didn't use this outright.
Though, this is where my config is heading to be and instead slowly making parts of my config based from this template.

* github:divnix/digga/[opts=repo], a flake utility library for your overengineered config.
I also stole parts of it for my custom library.
I may have to use this at some point. footnote:[Unfortunately, digga is considered to be a retired project as of 2023-07-09 so that may not be true.]

* github:hlissner/dotfiles/[hlissner's dotfiles], the original inspiration for this functional abomination of a configuration.
The very reason why I'm using NixOS after seeing their configuration and what it can be setup with one command.
Anyways, screw you for bringing me into this [.line-through]#hell# rabbit hole.
