{
  imports = [
    ./files/mutable-files.nix
    ./programs/kando.nix
    ./programs/pipewire.nix
    ./programs/pop-launcher.nix
    ./programs/borgmatic.nix
    ./programs/diceware.nix
    ./programs/nushell.nix
    ./programs/python.nix
    ./services/archivebox.nix
    ./services/borgbackup.nix
    ./services/borgmatic.nix
    ./services/bleachbit.nix
    ./services/distant.nix
    ./services/gallery-dl.nix
    ./services/gonic.nix
    ./services/ludusavi.nix
    ./services/matcha.nix
    ./services/openrefine.nix
    ./services/plover.nix
    ./services/yt-dlp.nix
  ];
}
