[[imports]]
path = "github.com/foo-dogsquared/website"

[[imports.mounts]]
source = "assets/scss/"
target = "assets/scss/"

[[imports.mounts]]
source = "assets/css/"
target = "assets/css/"

[[imports.mounts]]
source = "layouts/partials"
target = "layouts/partials"
excludeFiles = [ "footer.html" ]

[[imports.mounts]]
source = "layouts/_default"
target = "layouts/_default"
includeFiles = [ "baseof.html" ]

[[imports.mounts]]
source = "assets/svg/avatars/"
target = "static/icons/avatars/"

[[imports.mounts]]
source = "assets/svg/avatars/"
target = "assets/svg/avatars/"

[[imports.mounts]]
source = "i18n/"
target = "i18n/"

[[imports.mounts]]
source = "data/more-contentful/themes/"
target = "data/more-contentful/themes/"
