patterns:
    home: ENC[AES256_GCM,data:8wCxREEfMlZseot2UuN2JmOaoaWVbO++q21/WRIDu8Z2emC5ii93mY5Kl1CdgtgoXOWSF+HWmQB7g7pbilTDykKA0wue3UnGjxR9ST2uyJaFFpytAIDpOi/wV5zNEI76kg+Ly8N6LjVkLUhTF1qB9fhwGcFzxdFkSUlY2CTWloYGmABY+H3v8vgWbGy+MgKgw7FmzjmqJGpYosi1tqkNctOCDi8ExZG9slD60JYIrIstxmTWqPp2HpzHojeW5cSevTjNx0YY7JZQzOtog4a4AD7Ztrj7nhdS0qfeS7r6RjZrGpkC3d+nUPtEoqwH37xp+G3KvpiQTnVl4qwVBIezUWNPnXJ/eL4lySiue+0qhKVCdaG3/EaObP4vIOUv/8C1N7JVYlhq/Fqmgfukee3v33xjWWKxvN/IrxgKyzOT4a0YTuLYqIj4JaHu5O3lziFDYTuFtKPvIpj0MCbfB+NccE23BuPR6Dgj2mY5V2Gwjwi7R5NMd2I=,iv:aekk7RIqluAAB5+owNECPjZc6LhnBGBsN6eCTAoLklA=,tag:nvNepYWZLgNZUNylkeSBIQ==,type:str]
    keys: ENC[AES256_GCM,data:xxuamNHPWLpQyERawROxaRdUek6HoDypPK9zw9WGRJthk+7vtCWhyZLLndz0j0ST0H5mU9L9rwDJ4GiyKvPgAyk4iP4=,iv:FclOzefSaDDc+VXq/EMdKX95GfzInPvdKdaBqkNTQRI=,tag:p/0upm4ef/ESx0m9MUPROg==,type:str]
    root: ENC[AES256_GCM,data:MAwmT4t6GA9bK0lPKk/Qkv+keavU2VpVfmKaNqZ+7dLXJjEoEXi6LImbTlAL3bsn1RUPtb1yRWmdcD9wETOjOm7SuufG/HtxI1sJpZnmkUPJV+2I1ll5krEWp1/M1vQHNTgQ2gbJU99riORN4W0EDOeQEg2vMvzALRYW5LRrL/InDqfqzbqUSodb0Uwnt5IL9yQEJIOrIaqxeVRA9zLA6m9ri5dkYIk70hg7QyzDEGA1pzsp81odE6wHAP6yhg==,iv:Kiq7uDRVFwLSOFoEU4xOhsvmSMivO/5fQUc96zmzmD0=,tag:FCHnoIoNpMxsS2gacda/tw==,type:str]
repos:
    archives:
        password: ENC[AES256_GCM,data:FuPW5dgbt20+eOT4ulV653amUocILnSgc2sBYaeusXw=,iv:WZJYpYdWQzs8G23P4Zflhlxe/H1tShPvMjmFEiLHl4A=,tag:lZUC9JBIwhcEiBpPajaKUw==,type:str]
    hetzner-box:
        password: ENC[AES256_GCM,data:GuNsNiVGHyUPrkVMlUQfAEIs/1bGfp3qYseXi/T+lQ==,iv:qrTs+T89R8wzvCxKzYoJyVzBGMczIDqhqfXB93pyxBU=,tag:KdO2cQjMjkJviBF+/5wzdA==,type:str]
        ssh-key: ENC[AES256_GCM,data:b6A6ryV8gtBLWs0zje6KmTGvsMCDjS7KkisctZYkQ6Mt+1V5r49mVkgsZJF4zemK0FENR1usBeOQW9ylkmZD4attYrIp20KgMs7lmehpViE3xk8MA/m6TFUjR0bXh/FW+bwQ2JPFh09kmEmvPsj0gbGXp6Ine63PxQOPc2wZxxkgm1hjnDFeZVhknw5L3UrmvsOD2ex6lrCip6LwsKcz+9v4KRixQJkAQreALQ8lyw32FYKB8GwPsTSDjGpqiQAZWq1u8jEZcPmITW60qVH42V4jD0tny0HkQIaY5TpssPWbNrB1DPyKTtq1ZyRWRcTVtGQAGLcmcA2+vErdGDuM0YbvJmSbzRIj3EE9dR9gQJ19N1LRoJnQn2qLE5TovYFFa4V7tTx8GMa34dUmHfaIhotk+itCL/le9dhROdb2W1FabpRM7NkObJKdyV9HR88WpAZFr9wpnuOyEKW2qFFVqsPpmHP21VkKfbGJxm3LL6zw4MHN/WsFvfMF2NQCshOXixubQNiDaEQcMjlx3tS7easuB3Lavg3vQa4F,iv:hV4FupMtLb8lpe3JWlkbFLBu37kae06InNiZTOlppo0=,tag:k1rVBDz4mjD1ovxiTSEtZA==,type:str]
    external-hdd:
        password: ENC[AES256_GCM,data:P9LNQIs456JBWFJs1ARQHLiNeLWlkhPWaEgX431VYg5YNA==,iv:cN3v9jMZlHRVUHdhvXnDizl0GdpVlw5U70yYlxAv3ek=,tag:mYaq2M8xSBfl5+lAa1NNVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxna9vm7nx4g69s84qgjptxvuzszcypf2rfk4ss2lyhnpe3yxdnqusu6jp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVExxY094cElKaG9KVUVC
            R0R1RXd6YjViRnlpM2VKaDY3NlNUZXpoSEcwCithUUhzbERveVlRZm40bzQ0bitH
            OEh4MlRLNjdsQjYvNENZMk5DMytoMjAKLS0tIHV6NkdYUGN3d1RpNmFxTWY4YW1s
            emJQY1B4UHQvVDJxQlVlUjZXcW5hV2MKAqRYMFGWoXALeUeDoFCYFvCT8pIIRGk4
            xMZwLHvRWuZW+15DYGrfrA9+DOS6SZYEYQeApMFVWUdYMU/Xn6KZig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T04:49:56Z"
    mac: ENC[AES256_GCM,data:d/PpeuvmhHLNivielvfuSfUIQWuSYPd/CJrnuSWoWQxorZG9V7g3UnqMmb7mfISLj3HpC0Xgo1R/wV03hdaRoT2/JwG0Gl4ya9FJiO5jKiwkKVC5cFPvh26aRWTG9/qCzkymL+GC2vyqsvsYTXkq42Ef43tUmxGoFDGsbHzoAlw=,iv:LFIvVqBi4pQEhleaWdcfQI4jGzFksTlRXMgFfHbaaTM=,tag:fsNrZ4h0YmPhCP1XyD9LiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
