= Homepage

Hey there!
This is my documentation for my abomination of a NixOS configuration called "foodogsquared's NixOS config" book or "f(a)Nc(y)" config book for short.

.This St. Nixolas's reindeer cosplay is made with a tight budget but it's functionally identical, right?
image::./nix-snowflake-with-fds.svg[width=256px]

Why don't you start skimming the "book" by taking a glance at the table of contents over there.

[chat, Ezran, state=curious, role=reversed]
====
Why would you have an entire book on just your NixOS configuration?
This seems like overkill.
====

[chat, foodogsquared, state=cheeky]
====
Because **it is overkill** and that's what we're going for.
====

[chat, Ezran, state=disappointed, role=reversed]
====
And what is this book made of?
Hugo?
With Asciidoctor?
With a customized version of github:foo-dogsquared/hugo-theme-more-contentful[your own theme]?
OF ALL OPTIONS!?!

Why not use something like github:rust-lang/mdBook[mdBook]?
Or link:https://squidfunk.github.io/mkdocs-material/[mkdocs-material] that makes things eas-
====

[chat, Ezran, state=skeptical, role=reversed]
====
You know what, I'm not going to continue with this.
I think I know why.
====
