---
title: Channels support
---
= Channels support

While this primarily uses flakes as its main form of distribution, this project does keep some use cases for traditional channels.
It's not guaranteed to be good as xref:../../05-using-parts-of-my-configuration/index.adoc#using-my-config-with-flakes[Using my config with flakes] but it's an option.
Anyhow, there is a section for using my configuration with channels as shown in xref:../../05-using-parts-of-my-configuration/index.adoc#using-my-config-with-channels[Using my config with channels].

The entry point is found at github:{github-repo}[`./default.nix`, path=./default.nix, rev=master].

.`default.nix`
[source, nix]
----
include::../../../../../default.nix[]
----

As you can tell, it is made with github:edolstra/flake-compat[opts=repo].
This is to support both use cases easily at the expense of making the traditional method a bit more tedious such as the Nix project being completely locked in with its dependencies (thus you can't configure it with your own nixpkgs version). footnote:[Then again, the way it used to be before flakes already has a host of problems. This is the least of them.]
